backend:
  name: git-gateway
  branch: main # আপনার গিটহাব ব্রাঞ্চ যদি master হয় তবে master লিখবেন

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "series"
    label: "Series"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      
