backend:
  name: github
  repo: bdkabirkhan001-alt/Web-series
  branch: main
  base_url: https://decap-cms-oauth-pk.vercel.app
  auth_endpoint: /auth

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "series"
    label: "Series"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
